
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Removed tracker for boss:"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Removed tracker for boss:"]

