#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 30 02:11:03 AST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=\u00A7lE-LITE shaders 5.0.1.zip
enableShaders=true
