#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 30 17:41:19 AST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=
enableShaders=true
