#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 28 17:16:12 AST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=
enableShaders=true
